# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Modacity' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Modacity
  
  pod 'TPKeyboardAvoiding'
  pod 'ObjectMapper'
  
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  
  pod 'LGSideMenuController'
  
  pod 'GoogleSignIn'
  
  pod 'UITextView+Placeholder'
  
  pod 'SCSiriWaveformView'
  pod 'FDWaveformView'
  
  pod 'BWHorizontalTableView'
  
  target 'ModacityTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ModacityUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
