# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def shared_pods
    use_frameworks!
    
    pod 'TPKeyboardAvoiding'
    pod 'ObjectMapper'
    
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'Firebase/Database'
    
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
    
    pod 'LGSideMenuController'
    
    pod 'GoogleSignIn'
    
    pod 'UITextView+Placeholder'
    
    pod 'SCSiriWaveformView'
    pod 'FDWaveformView'
    
    pod 'BWHorizontalTableView'
    
    pod 'Amplitude-iOS', '~> 4.0.4'
    
    pod 'SwiftMessages'
    
    pod 'MBProgressHUD'
end

target 'Modacity' do
    shared_pods
end

target 'Modacity-Dev' do
    shared_pods
end

target 'ModacityTests' do
end

target 'ModacityUITests' do
end
